################################################################################
#####     MultiPlug configuration
################################################################################

MOTD: |
  &f=====================================================
  &c MultiPlug MOTD Sample
  &f=====================================================
