# This is MultiPlug's plugin.yml
# For more information refer to http://wiki.bukkit.org/Plugin_YAML
# This file uses maven resource filtering to fill in values at compile time
name: ${project.name}
version: ${project.version}
main: de.wumato.MultiPlug.MultiPlug
description: ${project.description}
authors: [wumato]
api-version: 1.13
commands:
  mp:
    description: Invokes different multiplug actions
    usage: /<command> [action]
permissions:
  mp.*:
    description: Gives access to all non-admin actions
    default: op
    children:
      mp.motd: true
      mp.announcement: true
      mp.version: true
      mp.ores: true
  mp.motd:
    description: Display current message of the day
  mp.announcement:
    description: Display current announcement text
  mp.version:
    description: Display MultiPlug version
  mp.ores:
    description: Display list of ores found nearby the player
  mp.reload:
    description: Reload MultiPlug configuration
